# Build mdBook documentation
# See: https://rust-lang.github.io/mdBook/index.html
name: Build mdBook Documentation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.36
    steps:
      - uses: actions/checkout@v4

      - name: Install mdBook
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          source "$HOME/.cargo/env"
          cargo install --version ${MDBOOK_VERSION} mdbook

      - name: Build with mdBook
        run: mdbook build

      - name: Upload book artifact
        uses: actions/upload-artifact@v4
        with:
          name: mdbook-output
          path: ./book/
